version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - epub
  - pdf

python:
  version: 3.8

  install:
      - method: pip
        path: sphinx==4.4.0
      - method: pip
        path: furo==2022.1.2
